<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Test</title>

   <base href="<?php echo Yaf_Registry::get("config")->application->domain?>" />

    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">

  </head>
  <body>
    <h1>
      <a onclick="history.go(-1)">返回</a>
      <a onclick="location.reload()">刷新</a>
    </h1>
 